import { Award, BookOpen, Heart, Sparkles } from "lucide-react";
import goldPortrait from "../assets/shivdayal-gold.png";
import { PageHero } from "../components/PageHero";
import { SectionHeading } from "../components/SectionHeading";

export function AboutPage() {
  return <><PageHero eyebrow="About" title={<>आस्था, ज्ञान और <span className="text-[#ae5028]">सेवा</span> का पथ</>} copy="श्री शिवदयाल तिवारी जी महाराज का परिचय, काशी-वाराणसी से जुड़ी आध्यात्मिक सेवा और सनातन मूल्यों के प्रति उनकी प्रतिबद्धता।" />
    <section className="section-space bg-[#fffdf8]"><div className="page-container grid items-center gap-14 lg:grid-cols-[.85fr_1.15fr] lg:gap-24"><div className="relative mx-auto w-full max-w-[390px]"><div className="absolute -inset-4 border border-[#b38a42]/45" /><div className="relative overflow-hidden bg-[#120807]"><img src={goldPortrait} className="h-[560px] w-full object-cover object-top" alt="Shri Shivdayal Tiwari Ji Maharaj" /></div></div><div><SectionHeading eyebrow="A humble introduction" title={<>दिव्य प्रेरणा से <span className="text-[#ae5028]">लोक-सेवा</span> तक</>} /><div className="mt-6 grid gap-5 text-sm leading-7 text-[#73594e]"><p>श्री श्री 1008 ब्रह्मर्षि श्री देवराहा बाबा सरकार के अभिष्ट कृपापात्र, श्री शिवदयाल तिवारी जी महाराज काशी, वाराणसी से ज्योतिषीय एवं आध्यात्मिक मार्गदर्शन प्रदान करते हैं।</p><p>मानसकिंकर, कथावाचक और ज्योतिषविद के रूप में कथा, प्रवचन तथा व्यक्तिगत संवाद के माध्यम से सनातन धर्म के शाश्वत मूल्यों के प्रति सहज जुड़ाव को महत्व दिया जाता है।</p><p>यह मंच आस्था, विचार और सदाचार के उन विषयों के लिए समर्पित है जो परिवार, समाज और व्यक्तिगत जीवन में सकारात्मक दिशा दें।</p></div></div></div></section>
    <section className="bg-[#f7eddb] py-20"><div className="page-container"><SectionHeading centered eyebrow="The intent" title={<>इस सेवा का <span className="text-[#ae5028]">उद्देश्य</span></>} /><div className="mt-12 grid gap-4 md:grid-cols-3"><Principle icon={Heart} title="आस्था का सम्मान" text="प्रत्येक साधक की भावना और परिस्थिति का सम्मान करते हुए संवाद।" /><Principle icon={BookOpen} title="वेद परंपरा" text="ज्योतिष एवं अनुष्ठान की वैदिक परंपरा से जुड़ा मार्गदर्शन।" /><Principle icon={Sparkles} title="सकारात्मक दिशा" text="जीवन में धैर्य, सदाचार और आशा को बल देने वाली दृष्टि।" /></div></div></section>
    <section className="section-space bg-[#fffdf8]"><div className="page-container"><p className="eyebrow">The path</p><h2 className="deva-heading mt-4 max-w-3xl text-4xl font-semibold text-[#3d1712] md:text-6xl">यात्रा के मुख्य <span className="text-[#ae5028]">आयाम</span></h2><div className="mt-12 border-t border-[#d8c5a1]/70">{[["01", "कथा एवं प्रवचन", "रामकथा और आध्यात्मिक प्रवचन के माध्यम से संवाद।"], ["02", "ज्योतिषीय मार्गदर्शन", "कुंडली, ग्रह संबंधी जिज्ञासाओं और वैदिक उपायों पर व्यक्तिगत परामर्श।"], ["03", "धार्मिक आयोजन", "पूजा, अनुष्ठान, सत्संग और विशेष अवसरों के लिए संपर्क।"]].map(([number, title, text]) => <div className="grid gap-3 border-b border-[#d8c5a1]/70 py-7 md:grid-cols-[120px_1fr_1.2fr]" key={number}><span className="display text-3xl text-[#b38a42]">{number}</span><h3 className="deva-heading text-2xl font-semibold text-[#4a1e16]">{title}</h3><p className="text-sm leading-6 text-[#765e53]">{text}</p></div>)}</div></div></section>
  </>;
}

function Principle({ icon: Icon, title, text }: { icon: typeof Award; title: string; text: string }) { return <article className="border border-[#d8c5a1]/65 bg-[#fffaf0] p-7 text-center"><span className="mx-auto grid size-12 place-items-center rounded-full border border-[#b38a42]/55 text-[#8f431f]"><Icon size={20} strokeWidth={1.4} /></span><h3 className="deva-heading mt-5 text-2xl font-semibold text-[#4a1e16]">{title}</h3><p className="mt-3 text-xs leading-6 text-[#755d52]">{text}</p></article>; }
