import { Check, MapPin, MessageCircle, Phone } from "lucide-react";
import { useState } from "react";
import { PageHero } from "../components/PageHero";
import { siteConfig } from "../data/siteConfig";

const eventTypes = ["कथा", "सत्संग", "भजन", "आध्यात्मिक प्रवचन", "सहयोग", "मीडिया", "अन्य"];

export function ContactPage() {
  const [complete, setComplete] = useState(false);
  return <><PageHero eyebrow="Contact" title={<>सादर <span className="text-[#ae5028]">आमंत्रित</span> हैं</>} copy="ज्योतिषीय परामर्श, कथा आयोजन, सत्संग अथवा विशेष धार्मिक अनुष्ठान के लिए संपर्क करें।" />
    <section className="section-space bg-[#fffdf8]"><div className="page-container grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">Connect with the team</p><h2 className="deva-heading mt-4 text-4xl font-semibold text-[#421912] md:text-5xl">संवाद से नई दिशा</h2><p className="mt-5 max-w-md text-sm leading-7 text-[#755d52]">अपनी जिज्ञासा या आयोजन का संक्षिप्त विवरण साझा करें। आप सीधे कॉल या व्हाट्सऐप से भी जुड़ सकते हैं।</p><div className="mt-9 grid gap-5"><a className="flex gap-3 text-[#4d2018]" href={`tel:${siteConfig.primaryPhone.replace(/\s/g, "")}`}><span className="grid size-10 shrink-0 place-items-center rounded-full border border-[#b38a42]/55 bg-[#fff6df] text-[#9c481f]"><Phone size={17} /></span><span><b className="block text-xs">कॉल करें</b><small className="mt-1 block text-xs text-[#7a5d4d]">{siteConfig.primaryPhone}<br />{siteConfig.alternatePhone}</small></span></a><div className="flex gap-3 text-[#4d2018]"><span className="grid size-10 shrink-0 place-items-center rounded-full border border-[#b38a42]/55 bg-[#fff6df] text-[#9c481f]"><MapPin size={17} /></span><span><b className="block text-xs">स्थान</b><small className="mt-1 block text-xs text-[#7a5d4d]">{siteConfig.hindiAddress}</small></span></div><a className="button button-dark w-fit" target="_blank" rel="noreferrer" href={`https://wa.me/${siteConfig.whatsapp}`}><MessageCircle size={15} /> व्हाट्सऐप पर बात करें</a></div></div>
      <form onSubmit={(event) => { event.preventDefault(); setComplete(true); }} className="quiet-card grid gap-4 p-6 md:grid-cols-2 md:p-8">{complete ? <div className="col-span-full grid min-h-80 place-items-center text-center"><div><span className="mx-auto grid size-14 place-items-center rounded-full bg-[#ebf5e5] text-[#4b8243]"><Check /></span><h2 className="deva-heading mt-5 text-4xl font-semibold text-[#3d1712]">धन्यवाद</h2><p className="mx-auto mt-3 max-w-sm text-sm leading-7 text-[#755d52]">आपका संदेश तैयार है। हमारी टीम से बात करने के लिए व्हाट्सऐप अथवा कॉल का विकल्प चुनें।</p><a className="button button-primary mt-6" href={`https://wa.me/${siteConfig.whatsapp}`} target="_blank" rel="noreferrer">व्हाट्सऐप खोलें</a></div></div> : <><Field label="नाम" name="name" required /><Field label="फोन नंबर" name="phone" type="tel" required /><Field label="ईमेल" name="email" type="email" /><Field label="शहर" name="city" /><label className="grid gap-1.5 text-[11px] font-bold text-[#69402b]">आयोजन का प्रकार<select className="h-11 border border-[#d9c8ad] bg-white px-3 text-sm font-normal outline-none focus:border-[#b85e2a]"><option>चुनें</option>{eventTypes.map((item) => <option key={item}>{item}</option>)}</select></label><Field label="पसंदीदा तिथि" name="date" type="date" /><label className="grid gap-1.5 text-[11px] font-bold text-[#69402b] md:col-span-2">आपका संदेश<textarea className="min-h-28 border border-[#d9c8ad] bg-white p-3 text-sm font-normal outline-none focus:border-[#b85e2a]" /></label><button type="submit" className="button button-primary md:col-span-2">संदेश तैयार करें</button><p className="md:col-span-2 text-[10px] leading-5 text-[#927765]">यह फ्रंटएंड फॉर्म API/CRM से जोड़ने के लिए तैयार है। जब तक API जोड़ी नहीं जाती, संदेश सीधे वेबसाइट से नहीं भेजा जाता।</p></>}</form>
    </div></section>
  </>;
}

function Field({ label, name, type = "text", required = false }: { label: string; name: string; type?: string; required?: boolean }) { return <label className="grid gap-1.5 text-[11px] font-bold text-[#69402b]">{label}<input required={required} name={name} type={type} className="h-11 border border-[#d9c8ad] bg-white px-3 text-sm font-normal outline-none focus:border-[#b85e2a]" /></label>; }
