import { motion } from "framer-motion";
import { BookOpenCheck, HeartHandshake, Phone, Quote } from "lucide-react";
import { useEffect } from "react";
import blueContactPortrait from "../assets/shivdayal-contact-blue.png";
import ramKathaPortrait from "../assets/shivdayal-ram-katha.png";
import redPortrait from "../assets/shivdayal-red.png";
import { KundliCalculator } from "../components/KundliCalculator";
import { Panchang } from "../components/Panchang";
import { services, siteConfig } from "../data/siteConfig";
import type { Language } from "../utils/vedic";

type Props = { language: Language; setLanguage: (language: Language) => void };

const text = {
  hi: { identity: "मानसकिंकर • कथावाचक • ज्योतिषविद", kicker: "काशी • वाराणसी", title: <>आस्था से <span className="text-[#c7642d]">प्रकाशित</span> जीवन की ओर</>, intro: "कथा, भक्ति और ज्योतिषीय ज्ञान के माध्यम से जीवन की जिज्ञासाओं पर सहज, सम्मानजनक और वैदिक दृष्टि से संवाद।", whatsapp: "व्हाट्सऐप पर संपर्क करें", call: "कॉल करें", journey: "परिचय", journeyTitle: <>ज्ञान, भक्ति और <span className="text-[#b65228]">सेवा</span> का एक पथ</>, journeyOne: "श्री श्री 1008 ब्रह्मर्षि श्री देवराहा बाबा सरकार के अभिष्ट कृपापात्र, श्री शिवदयाल तिवारी जी महाराज काशी-वाराणसी से ज्योतिषीय एवं आध्यात्मिक मार्गदर्शन प्रदान करते हैं।", journeyTwo: "जीवन के प्रश्नों पर वैदिक दृष्टि से संवाद करते हुए, कथा और प्रवचन के माध्यम से सनातन मूल्यों का संदेश साझा करना इस सेवा का विनम्र उद्देश्य है।", services: "सेवाएँ", servicesTitle: <>जीवन के प्रश्नों के लिए <span className="text-[#b65228]">सहज मार्गदर्शन</span></>, kathaKicker: "कथा • सत्संग • अनुष्ठान", kathaTitle: "श्रीराम कथा के पावन आयोजन हेतु", kathaText: "घर, मंदिर अथवा विशेष धार्मिक अवसर पर श्रीराम कथा, सत्संग, प्रवचन एवं वैदिक अनुष्ठान के लिए संपर्क करें।", invite: "कथा हेतु आमंत्रित करें", contact: "संपर्क", contactTitle: "आइए, संवाद आरंभ करें", contactText: "ज्योतिषीय परामर्श या किसी धार्मिक आयोजन के लिए सीधे कॉल अथवा व्हाट्सऐप पर जुड़ें।", footer: "ज्योतिषीय एवं आध्यात्मिक मार्गदर्शन • काशी, वाराणसी", lang: "EN" },
  en: { identity: "Manaskinkar • Kathavachak • Jyotishvid", kicker: "Kashi • Varanasi", title: <>Towards a life <span className="text-[#c7642d]">lit by faith</span></>, intro: "A considered Vedic conversation for life's questions through Katha, devotion, and astrological wisdom.", whatsapp: "Connect on WhatsApp", call: "Call now", journey: "Introduction", journeyTitle: <>A path of wisdom, devotion &amp; <span className="text-[#b65228]">service</span></>, journeyOne: "Blessed disciple of Shri Shri 1008 Brahmarshi Shri Devaraha Baba Sarkar, Shri Shivdayal Tiwari Ji Maharaj offers astrological and spiritual guidance from Kashi, Varanasi.", journeyTwo: "The humble purpose of this service is to share Sanatan values through Katha, discourses, and thoughtful Vedic conversation on life's questions.", services: "Guidance", servicesTitle: <>Support for life's <span className="text-[#b65228]">important questions</span></>, kathaKicker: "Katha • Satsang • Rituals", kathaTitle: "For a sacred Shri Ram Katha gathering", kathaText: "Get in touch for Shri Ram Katha, Satsang, spiritual discourse, and Vedic rituals at a home, temple, or special religious occasion.", invite: "Invite for Katha", contact: "Contact", contactTitle: "Let the conversation begin", contactText: "Connect directly by call or WhatsApp for a consultation or religious gathering.", footer: "Astrological & spiritual guidance • Kashi, Varanasi", lang: "हिंदी" },
};

export function HomePage({ language, setLanguage }: Props) {
  const copy = text[language];
  useEffect(() => {
    document.documentElement.lang = language;
    document.title = language === "hi" ? "श्री शिवदयाल तिवारी जी महाराज | काशी" : "Shri Shivdayal Tiwari Ji Maharaj | Kashi";
  }, [language]);

  return <div className="bg-[#fffdf8] text-[#301713]">
    <section className="grain relative overflow-hidden bg-[#fbf3e2]">
      <div className="absolute -left-24 top-16 size-[440px] rounded-full border border-[#b58d47]/20" />
      <div className="absolute right-0 top-0 h-full w-[39%] bg-[#4e1016] max-lg:hidden" />
      <div className="page-container relative">
        <div className="flex items-center justify-between gap-4 py-5">
          <div><p className="display text-lg font-semibold text-[#491912] sm:text-2xl">{siteConfig.hindiName}</p><p className="mt-0.5 text-[10px] font-bold uppercase tracking-[.17em] text-[#9b6333]">{copy.identity}</p></div>
          <button onClick={() => setLanguage(language === "hi" ? "en" : "hi")} className="border border-[#b38a42]/65 bg-[#fff9ea] px-3 py-2 text-xs font-bold text-[#5c2117] hover:bg-[#ffe9bb]">{copy.lang}</button>
        </div>
        <div className="gold-rule" />
      </div>
      <div className="page-container relative grid items-end gap-7 pb-0 pt-10 lg:grid-cols-[1fr_.95fr] lg:pt-16">
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .7 }} className="relative z-10 pb-12 lg:pb-24">
          <p className="eyebrow">{copy.kicker}</p><h1 className="deva-heading mt-5 max-w-2xl text-5xl font-semibold text-[#3d1711] sm:text-6xl lg:text-[4.5rem]">{copy.title}</h1><p className="mt-6 max-w-xl text-base leading-8 text-[#755a4c]">{copy.intro}</p>
          <div className="mt-8 flex flex-wrap gap-3"><a href={`https://wa.me/${siteConfig.whatsapp}`} target="_blank" rel="noreferrer" className="inline-flex min-h-12 items-center justify-center gap-2 bg-[#25D366] px-5 text-sm font-bold text-[#073a1d] shadow-[0_12px_25px_rgba(19,130,69,.18)] transition hover:-translate-y-0.5 hover:bg-[#4ade80]"><MessageCircle size={17} />{copy.whatsapp}</a><a href={`tel:${siteConfig.primaryPhone.replace(/\s/g, "")}`} className="button button-outline !text-sm"><Phone size={15} />{copy.call}</a></div>
        </motion.div>
        <motion.div initial={{ opacity: 0, scale: .96 }} animate={{ opacity: 1, scale: 1 }} transition={{ delay: .08, duration: .8 }} className="relative min-h-[440px] self-end lg:min-h-[590px]"><div className="absolute inset-x-[9%] bottom-0 h-[91%] rounded-t-full border border-[#e4c466]/60 bg-[radial-gradient(ellipse_at_center,#a54e28_0%,#68141a_57%,#3f090e_100%)]" /><div className="absolute inset-x-[18%] bottom-0 h-[83%] rounded-t-full border border-[#f4d780]/30" /><img src={redPortrait} alt="Shri Shivdayal Tiwari Ji Maharaj" className="absolute inset-x-0 bottom-0 z-[1] h-[99%] w-full object-contain object-bottom drop-shadow-[0_23px_25px_rgba(24,2,0,.37)]" /><span className="absolute right-[9%] top-[20%] z-[2] grid size-12 place-items-center rounded-full border border-[#efc766]/80 bg-[#4e1016] text-[#f5d276]">ॐ</span></motion.div>
      </div>
    </section>

    <section className="border-y border-[#dcc9a2] bg-[#fff9ed]"><div className="page-container grid text-center sm:grid-cols-3"><Stamp top={language === "hi" ? "काशी • वाराणसी" : "Kashi • Varanasi"} bottom={language === "hi" ? "सनातन परंपरा की पावन भूमि से" : "From the sacred land of Sanatan tradition"} /><Stamp top={language === "hi" ? "प्रथम 10–15 मिनट" : "First 10–15 minutes"} bottom={language === "hi" ? "प्रारंभिक बातचीत निःशुल्क" : "Initial conversation is complimentary"} /><Stamp top={language === "hi" ? "कुंडली एवं परामर्श" : "Kundli & consultation"} bottom={language === "hi" ? "सीधे व्हाट्सऐप पर संपर्क करें" : "Connect directly on WhatsApp"} last /></div></section>

    <KundliCalculator language={language} />

    <section className="section-space bg-[#fffdf8]"><div className="page-container grid items-start gap-10 lg:grid-cols-[.9fr_1.1fr]"><Panchang language={language} /><div className="relative overflow-hidden bg-[#f5e7cf] p-7 sm:p-10"><div className="absolute -right-12 -top-20 size-56 rounded-full border border-[#b38a42]/30" /><div className="relative"><p className="eyebrow">{copy.journey}</p><h2 className="deva-heading mt-4 max-w-xl text-4xl font-semibold text-[#3f1712] md:text-5xl">{copy.journeyTitle}</h2><p className="mt-5 max-w-xl text-base leading-8 text-[#73594e]">{copy.journeyOne}</p><p className="mt-4 max-w-xl text-base leading-8 text-[#73594e]">{copy.journeyTwo}</p><div className="mt-7 grid gap-3 sm:grid-cols-2"><Highlight icon={BookOpenCheck} text={language === "hi" ? "कथा एवं प्रवचन" : "Katha & discourses"} /><Highlight icon={HeartHandshake} text={language === "hi" ? "ज्योतिषीय मार्गदर्शन" : "Astrological guidance"} /></div></div></div></div></section>

    <section className="section-space bg-[#f7eddc]"><div className="page-container"><p className="eyebrow">{copy.services}</p><h2 className="deva-heading mt-4 max-w-3xl text-4xl font-semibold text-[#3e1712] md:text-5xl">{copy.servicesTitle}</h2><div className="mt-10 grid gap-px overflow-hidden border border-[#d9c5a2]/65 bg-[#d9c5a2]/65 sm:grid-cols-2 lg:grid-cols-4">{services.map((service, index) => <motion.article initial={{ opacity: 0, y: 14 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * .04 }} key={service.title} className="relative min-h-[210px] bg-[#fffdf8] p-6"><service.icon className="text-[#9a4823]" size={22} strokeWidth={1.45} /><p className="mt-7 text-[11px] font-bold uppercase tracking-[.12em] text-[#a6753e]">{service.en}</p><h3 className="deva-heading mt-2 text-2xl font-semibold text-[#4a1e17]">{language === "hi" ? service.title : service.en}</h3><p className="mt-3 text-sm leading-6 text-[#795f54]">{language === "hi" ? service.description : service.enDescription}</p></motion.article>)}</div></div></section>

    <section className="grain relative overflow-hidden bg-[#4e1016] py-16 text-[#fff5df] sm:py-20 md:py-28"><div className="absolute right-0 top-0 h-full w-1/2 bg-[radial-gradient(circle_at_center,rgba(196,112,41,.32),transparent_61%)]" /><div className="page-container relative grid items-center gap-10 sm:gap-12 lg:grid-cols-[.88fr_1.12fr]"><div className="relative mx-auto aspect-[4/5] w-full max-w-[380px] overflow-hidden border border-[#efc766]/50 bg-[#2a090b] shadow-[0_24px_50px_rgba(0,0,0,.24)]"><img src={ramKathaPortrait} alt="Shri Shivdayal Tiwari Ji Maharaj holding Shri Ramcharitmanas" className="h-full w-full object-cover object-center" /></div><div className="min-w-0 text-center lg:text-left"><p className="inline-flex flex-wrap items-center justify-center gap-x-2 gap-y-1 border border-[#efc766]/55 bg-[#260609]/35 px-4 py-2 text-base font-extrabold leading-6 tracking-[.04em] text-[#f6d67e] lg:justify-start">{copy.kathaKicker}</p><h2 className="deva-heading mt-5 max-w-2xl text-[2.6rem] font-semibold leading-[1.26] sm:text-6xl lg:text-7xl">{copy.kathaTitle}</h2><p className="mx-auto mt-5 max-w-xl text-lg leading-8 text-[#f3dfb2] lg:mx-0">{copy.kathaText}</p><a href={`https://wa.me/${siteConfig.whatsapp}`} target="_blank" rel="noreferrer" className="mt-8 inline-flex min-h-14 items-center justify-center gap-2 bg-[#25D366] px-6 text-base font-bold text-[#073a1d] shadow-[0_12px_25px_rgba(19,130,69,.20)] transition hover:-translate-y-0.5 hover:bg-[#50dd86]"><MessageCircle size={19} />{copy.invite}</a></div></div></section>

    <section className="section-space bg-[#fffdf8]"><div className="page-container grid items-center gap-12 lg:grid-cols-[1.05fr_.95fr]"><div><p className="eyebrow">{copy.contact}</p><h2 className="deva-heading mt-4 text-5xl font-semibold text-[#3d1712]">{copy.contactTitle}</h2><p className="mt-5 max-w-xl text-base leading-8 text-[#73594e]">{copy.contactText}</p><div className="mt-8 grid gap-4"><a href={`tel:${siteConfig.primaryPhone.replace(/\s/g, "")}`} className="flex items-center gap-4 border border-[#dac7a5] bg-[#fff9ed] p-4"><Phone className="text-[#a24e27]" size={20} /><span><b className="block text-sm text-[#4c1e17]">{siteConfig.primaryPhone}</b><small className="mt-1 block text-xs text-[#795b4b]">{siteConfig.alternatePhone}</small></span></a><a href={`https://wa.me/${siteConfig.whatsapp}`} target="_blank" rel="noreferrer" className="flex items-center gap-4 border border-[#9bdfa9] bg-[#effcf2] p-4"><span className="grid size-10 place-items-center rounded-full bg-[#25D366] text-[#073a1d]"><MessageCircle size={20} /></span><span><b className="block text-sm text-[#195d31]">{copy.whatsapp}</b><small className="mt-1 block text-xs text-[#39764c]">{language === "hi" ? "शीघ्र संवाद के लिए" : "For a quick conversation"}</small></span></a></div></div><div className="relative mx-auto w-full max-w-[390px]"><div className="absolute -inset-4 border border-[#b38a42]/45" /><img src={blueContactPortrait} alt="Shri Shivdayal Tiwari Ji Maharaj" className="relative h-[460px] w-full bg-[#4e1016] object-cover object-top" /></div></div></section>

    <footer className="bg-[#27070a] py-8 text-[#f5dfae]"><div className="page-container flex flex-col items-center justify-between gap-3 text-center sm:flex-row sm:text-left"><div><p className="display text-xl font-semibold text-[#fff4dc]">{siteConfig.hindiName}</p><p className="mt-1 text-xs text-[#d1ad6c]">{copy.footer}</p></div><p className="text-xs text-[#c9a167]">© {new Date().getFullYear()} {siteConfig.hindiName}</p></div></footer>
    <a aria-label="WhatsApp" href={`https://wa.me/${siteConfig.whatsapp}`} target="_blank" rel="noreferrer" className="fixed bottom-5 right-5 z-30 grid size-14 place-items-center rounded-full bg-[#25D366] text-[#073a1d] shadow-[0_12px_30px_rgba(10,126,54,.4)] transition hover:scale-105"><MessageCircle size={26} /></a>
  </div>;
}

function Stamp({ top, bottom, last = false }: { top: string; bottom: string; last?: boolean }) { return <div className={`px-6 py-6 ${last ? "" : "border-b border-[#dcc9a2] sm:border-b-0 sm:border-r"}`}><p className="display text-2xl font-semibold text-[#522017]">{top}</p><p className="mt-1 text-xs text-[#85654a]">{bottom}</p></div>; }
function Highlight({ icon: Icon, text }: { icon: typeof Quote; text: string }) { return <div className="flex items-center gap-3 border border-[#d7bd8f] bg-[#fff9ee] p-3 text-sm font-bold text-[#63311d]"><Icon className="text-[#a14c25]" size={17} />{text}</div>; }
function MessageCircle({ size = 20 }: { size?: number }) { return <svg aria-hidden="true" viewBox="0 0 32 32" width={size} height={size} fill="none"><path fill="#fff" d="M16 3.2a12.72 12.72 0 0 0-10.9 19.28L3.3 29l6.71-1.76A12.73 12.73 0 1 0 16 3.2Zm0 22.94c-1.96 0-3.85-.53-5.5-1.53l-.4-.24-3.98 1.04 1.06-3.88-.26-.4A10.6 10.6 0 1 1 16 26.14Z" /><path fill="#fff" d="M22.23 18.3c-.34-.17-2-1-2.31-1.1-.31-.12-.54-.17-.77.17-.22.34-.88 1.1-1.08 1.32-.2.23-.4.26-.74.09-2.01-1-3.32-1.8-4.64-4.1-.35-.61.35-.57 1-1.9.11-.23.06-.43-.03-.6-.09-.17-.77-1.85-1.06-2.54-.28-.67-.57-.58-.77-.59h-.66c-.23 0-.6.09-.91.43-.31.34-1.2 1.18-1.2 2.88 0 1.7 1.23 3.34 1.4 3.57.17.22 2.42 3.7 5.86 5.2.82.36 1.46.57 1.96.73.82.26 1.56.22 2.15.13.66-.1 2- .82 2.28 1.62.28.8.28 1.49.2 1.63-.08.14-.3.22-.63.4Z" /></svg>; }
